### ISSUE TITLE
/pages/ getting saved as /ages

### ISSUE THREAD

**Issue by tylerecouture** [timonweb/django-url-or-relative-url-field#2]
Hi! I'm trying out your field, thanks for it! However, when I try to link to a relative url `/pages/` it saves as `/ages/`. any idea why the p is being stripped?

**Comment by jcschefer** [comment]
Not a maintainer, but this looks like a bug. If you look [here](https://github.com/timonweb/django-url-or-relative-url-field/blob/master/url_or_relative_url_field/forms.py#L22) it calls `lstrip('http:///')` which strips all 'h's, 't's, 'p's, and '/'s from the left side of 'value'. I think fixing this issue would be as easy as replacing that `value.lstrip('http:///')` with `value[8:]`

**Comment by timonweb** [comment]
Hi Guys, fixed. Sorry for this taking that long to close, just didn't have enough time.
